[package]
name = "rsa-performance"
version = "0.1.0"
edition = "2021"

[dependencies]
rsa = "0.9"
rand = "0.8"
criterion = { version = "0.5", features = ["html_reports"] }

[[bench]]
name = "benchmark_manual"
harness = false

[[bench]]
name = "benchmark_lib"
harness = false 